### ISSUE TITLE
Infomaniak password leak

### ISSUE THREAD

**Issue by johannlaqua** [Drx85/p5_personnal_blog#18]
https://github.com/Drx85/p5_personnal_blog/blob/1c2c7c2e134de69041039019272bcf6eaa837ba7/app/Config.php#L14

Hello, i am the CISO at Infomaniak.com and we found that your smtp password is saved in plain text here.

Can you change it fast ? thx

**Comment by johannlaqua** [comment]
@Drx85 please can you check my comment ?

**Comment by Drx85** [comment]
Hello,
Thank you for your concern ! But I have modified my Infomaniak password before commiting this.
